###################### Filebeat Configuration Example #########################

# This file is an example configuration file highlighting only the most common
# options. The filebeat.reference.yml file from the same directory contains all the
# supported options with more comments. You can use it as a reference.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/filebeat/index.html

# For more available modules and options, please see the filebeat.reference.yml sample
# configuration file.

# ============================== Filebeat inputs ===============================

filebeat.inputs:
  # filestream is an input for collecting log messages from files.
  - type: filestream
    id: phone-log
    enabled: true
    paths:
      - ${logDir}/harmony/*/*/*/hilog.*.txt
      - ${logDir}/harmony/*/*/hilog.*.txt
      - ${logDir}/harmony/*/hilog.*.txt
      - ${logDir}/harmony/realtime/*/hilog.*.txt
      - ${logDir}/android/*/*/*/hilog.*.txt
      - ${logDir}/android/*/*/hilog.*.txt
      - ${logDir}/android/*/hilog.*.txt
      - ${logDir}/android/realtime/*/hilog.*.txt

    timezone: Asia/Shanghai
    fields_under_root: true
    fields:
      logType: phone-log

    processors:
      - fingerprint:
          fields: [ "message" ]
          target_field: "@metadata._id"
      - script:
          lang: javascript
          file: ${scriptPath}/js/splitBaseFields.js

  # filestream is an input for collecting log messages from files.
  - type: filestream
    id: ohosStudy-log
    enabled: true
    paths:
      - ${logDir}/harmony/*/*/*/hilog.*.txt
      - ${logDir}/harmony/*/*/hilog.*.txt
      - ${logDir}/harmony/*/hilog.*.txt
      - ${logDir}/harmony/realtime/*/hilog.*.txt

    timezone: Asia/Shanghai
    fields_under_root: true
    fields:
      logType: ohosStudy

    parsers:
      - include_message.patterns: [ "06666/ohosStudy" ]
      - multiline:
          type: pattern
          pattern: Segment Data\[[1-9]\d*\]
          negate: false
          match: after
          skip_newline: true

    processors:
      - fingerprint:
          fields: [ "message" ]
          target_field: "@metadata._id"
      - script:
          lang: javascript
          file: ${scriptPath}/js/splitBaseFields.js
      - if:
          contains:
            message: "Segment Data"
        then:
          - script:
              lang: javascript
              file: ${scriptPath}/js/handleSegmentData.js
      - if:
          contains:
            message: "@startuml"
        then:
          - script:
              lang: javascript
              file: ${scriptPath}/js/handleUmlData.js

# ============================== Filebeat modules ==============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1
  #index.codec: best_compression
  #_source.enabled: false


# ================================== General ===================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
#name:

# The tags of the shipper are included in their field with each
# transaction published.
#tags: ["service-X", "web-tier"]

# Optional fields that you can specify to add additional information to the
# output.
#fields:
#  env: staging

# ================================= Dashboards =================================
# These settings control loading the sample dashboards to the Kibana index. Loading
# the dashboards is disabled by default and can be enabled either by setting the
# options here or by using the `setup` command.
#setup.dashboards.enabled: false

# The URL from where to download the dashboard archive. By default, this URL
# has a value that is computed based on the Beat name and version. For released
# versions, this URL points to the dashboard archive on the artifacts.elastic.co
# website.
#setup.dashboards.url:

# =================================== Kibana ===================================

# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.
setup.kibana:

  # Kibana Host
  # Scheme and port can be left out and will be set to the default (http and 5601)
  # In case you specify and additional path, the scheme is required: http://localhost:5601/path
  # IPv6 addresses should always be defined as: https://[2001:db8::1]:5601
  host: "localhost:5601"

# ================================== Outputs ===================================

# Configure what output to use when sending the data collected by the beat.

# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: [ "localhost:9200" ]

  # Protocol - either `http` (default) or `https`.
  #protocol: "https"

  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  #username: "elastic"
  #password: "changeme"

# ================================= Processors =================================
processors:
  - script:
      lang: javascript
      file: ${scriptPath}/js/generateFileInfo.js
  - timestamp:
      field: temp_time
      layouts:
        - '2006-01-02 15:04:05'
        - '2006-01-02 15:04:05.999'
      test:
        - '2019-06-22 16:33:51'
        - '2019-11-18 04:59:51.123'
  - drop_fields:
      fields: [ 'temp_time', 'agent', 'ecs' ]

